title: El Atajo
description: Atajos prácticos para la vida, el dinero, los negocios y la tecnología. Del canal de YouTube ELATAJO.
lang: es
url: https://iv2s4.github.io
baseurl: /el-atajo-render
youtube: https://www.youtube.com/channel/UCHm8KOaK53B4E68nbNBcfOw?sub_confirmation=1
permalink: /:year/:month/:slug/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
